name: Run shell commands
on: [push]
jobs:
  run-shell-command:
   runs-on: ubuntu-latest
   name: Run a shell command and print some text
   steps:
    -name: echo a sting
     run: echo "Hello, Welcome to Agentic DevSecOps"

